<a href="https://colab.research.google.com/github/ccbeltran/Talento_Tech/blob/main/Trabajo_Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

In [5]:

# Importar el archivo desde la ruta personal de Google Drive
from google.colab import drive # Traemos la clase drive, dentro del módulo colab, del paquete google
drive.mount('/content/drive')  # Establecemos la conexión através del método mount

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [10]:
#Establezco la conexión con mi fuente y con el dataset de prueba Dataset1.csv
ruta = '/content/drive/MyDrive/TalentoTech/Python/Base.csv'
df = pd.read_csv(ruta, nrows=20)
print(df)

    codigo_camara camara_comercio  matricula  inscripcion_proponente  \
0               1         ARMENIA       9249                       0
1               1         ARMENIA       9251                       0
2               1         ARMENIA       9253                       0
3               1         ARMENIA       9255                       0
4               1         ARMENIA       9257                       0
5              54    DOSQUEBRADAS      39592                       0
6               4          BOGOTA    2887840                       0
7               4          BOGOTA    2727102                       0
8               8            CALI    1150327                       0
9              23           HUILA     379204                       0
10              8            CALI     990092                       0
11              4          BOGOTA    1138528                       0
12              3    BARRANQUILLA     791579                       0
13              4          BOGOTA    2819057                       0
14             40   VILLAVICENCIO     361812                       0
15             32     SANTA MARTA     202551                       0
16              4          BOGOTA    2995480                       0
17              4          BOGOTA    2227423                       0
18              4          BOGOTA    2784855                       0
19             57        SAN JOSE      25725                       0

                                         razon_social primer_apellido  \
0                             RAMIREZ DE OSPINA MARIA             NaN
1                              LONDONO GALLEGO DANILO             NaN
2                           ARTEAGA RAMIREZ PEDRO NEL             NaN
3                              ZAPATA ARRUBLA EDUARDO             NaN
4                           MENDEZ MENDEZ PEDRO PABLO             NaN
5                           GARCES GARCES GRESISMANDA          GARCES
6                        DAVID LEONARDO ZARAMA DAVILA             NaN
7   M Y M ASESORES INMOBILIARIOS SAS - EN LIQUIDACION             NaN
8                    ARANA REYES ASOCIADOS S.A.S. BIC             NaN
9                           MARIA VALENTINA RAMOS UNI           RAMOS
10                      ROJAS SANCHEZ JAVIER DE JESUS           ROJAS
11                               OSANA  ROJAS CORDOBA             NaN
12                         CARDONA HERRERA JULIO JOSE         CARDONA
13   THE LIFE GAME HOLDING GROUP SAS - EN LIQUIDACION             NaN
14                            LUZ GLADYS CORREA REYES          CORREA
15                    HERNANDEZ DURAN LORENA PATRICIA       HERNANDEZ
16                                   ALEXANDER  MUNAR             NaN
17               EPIK CONSULTING SAS - EN LIQUIDACION             NaN
18                     ANGELA PATRICIA GUERRERO DEVIA             NaN
19                              ELSA BONILLA GONZALEZ         BONILLA

   segundo_apellido                     primer_nombre segundo_nombre  \
0               NaN                               NaN            NaN
1               NaN                               NaN            NaN
2               NaN                               NaN            NaN
3               NaN                               NaN            NaN
4               NaN                               NaN            NaN
5            GARCES                       GRESISMANDA            NaN
6               NaN                               NaN            NaN
7               NaN                               NaN            NaN
8               NaN  ARANA REYES ASOCIADOS S.A.S. BIC            NaN
9               UNI                             MARIA      VALENTINA
10          SANCHEZ                            JAVIER       DE JESUS
11              NaN                               NaN            NaN
12          HERRERA                             JULIO           JOSE
13              NaN                               NaN            NaN
14            REYES                               LUZ         GLADYS
15            DURAN                            LORENA       PATRICIA
16              NaN                               NaN            NaN
17              NaN                               NaN            NaN
18              NaN                               NaN            NaN
19         GONZALEZ                              ELSA            NaN

                        sigla  ...  codigo_organizacion_juridica  \
0                         NaN  ...                             1
1                         NaN  ...                             1
2                         NaN  ...                             1
3                         NaN  ...                             1
4                         NaN  ...                             1
5                         NaN  ...                             1
6                         NaN  ...                             1
7   PORVENIR INMOBILIARIA SAS  ...                            16
8                         NaN  ...                            16
9                         NaN  ...                             1
10                        NaN  ...                             1
11                        NaN  ...                             1
12                        NaN  ...                             1
13                        NaN  ...                            16
14                        NaN  ...                             1
15                        NaN  ...                             1
16                        NaN  ...                             1
17                        NaN  ...                            16
18                        NaN  ...                             1
19                        NaN  ...                             1

                        organizacion_juridica  codigo_categoria_matricula  \
0                             PERSONA NATURAL                           0
1                             PERSONA NATURAL                           0
2                             PERSONA NATURAL                           0
3                             PERSONA NATURAL                           0
4                             PERSONA NATURAL                           0
5                             PERSONA NATURAL                           0
6                             PERSONA NATURAL                           0
7   SOCIEDADES POR ACCIONES SIMPLIFICADAS SAS                           1
8   SOCIEDADES POR ACCIONES SIMPLIFICADAS SAS                           1
9                             PERSONA NATURAL                           0
10                            PERSONA NATURAL                           0
11                            PERSONA NATURAL                           0
12                            PERSONA NATURAL                           0
13  SOCIEDADES POR ACCIONES SIMPLIFICADAS SAS                           1
14                            PERSONA NATURAL                           0
15                            PERSONA NATURAL                           0
16                            PERSONA NATURAL                           0
17  SOCIEDADES POR ACCIONES SIMPLIFICADAS SAS                           1
18                            PERSONA NATURAL                           0
19                            PERSONA NATURAL                           0

                             categoria_matricula  codigo_estado_matricula  \
0                                PERSONA NATURAL                        3
1                                PERSONA NATURAL                        3
2                                PERSONA NATURAL                        3
3                                PERSONA NATURAL                        3
4                                PERSONA NATURAL                        3
5                                PERSONA NATURAL                        1
6                                PERSONA NATURAL                        3
7   SOCIEDAD ó PERSONA JURIDICA PRINCIPAL ó ESAL                        1
8   SOCIEDAD ó PERSONA JURIDICA PRINCIPAL ó ESAL                        5
9                                PERSONA NATURAL                        1
10                               PERSONA NATURAL                        3
11                               PERSONA NATURAL                        3
12                               PERSONA NATURAL                        1
13  SOCIEDAD ó PERSONA JURIDICA PRINCIPAL ó ESAL                        1
14                               PERSONA NATURAL                        1
15                               PERSONA NATURAL                        1
16                               PERSONA NATURAL                        3
17  SOCIEDAD ó PERSONA JURIDICA PRINCIPAL ó ESAL                        1
18                               PERSONA NATURAL                        3
19                               PERSONA NATURAL                        1

    estado_matricula  clase_identificacion_RL  \
0          CANCELADA                      NaN
1          CANCELADA                      NaN
2          CANCELADA                      NaN
3          CANCELADA                      NaN
4          CANCELADA                      NaN
5             ACTIVA                      NaN
6          CANCELADA                      NaN
7             ACTIVA     CEDULA DE CIUDADANIA
8        NO ASIGNADO                      NaN
9             ACTIVA                      NaN
10         CANCELADA                      NaN
11         CANCELADA                      NaN
12            ACTIVA                      NaN
13            ACTIVA     CEDULA DE CIUDADANIA
14            ACTIVA                      NaN
15            ACTIVA                      NaN
16         CANCELADA                      NaN
17            ACTIVA    CEDULA DE EXTRANJERIA
18         CANCELADA                      NaN
19            ACTIVA                      NaN

    Num Identificacion Representante Legal  \
0                                      NaN
1                                      NaN
2                                      NaN
3                                      NaN
4                                      NaN
5                                      NaN
6                                      NaN
7                             5.258191e+07
8                                      NaN
9                                      NaN
10                                     NaN
11                                     NaN
12                                     NaN
13                            1.032385e+09
14                                     NaN
15                                     NaN
16                                     NaN
17                            3.693690e+05
18                                     NaN
19                                     NaN

                   Representante Legal            fecha_actualizacion
0                                  NaN  2020/11/14 05:28:48.583000000
1                                  NaN  2020/11/14 05:28:49.110000000
2                                  NaN  1900/01/01 00:00:00.000000000
3                                  NaN  2020/11/14 05:28:49.663000000
4                                  NaN  2020/11/14 05:28:50.250000000
5                                  NaN  2024/02/20 09:55:28.830000000
6                                  NaN  2022/04/27 11:18:11.103000000
7          MARTHA ROCIO ORTIZ GONZALEZ  2022/04/27 18:36:57.127000000
8                                  NaN  2022/04/22 16:01:51.343000000
9                                  NaN  2023/09/23 07:03:01.037000000
10                                 NaN  2022/04/23 17:23:04.653000000
11                                 NaN  2022/10/03 11:08:28.750000000
12                                 NaN  2023/09/20 12:56:46.670000000
13  JHONATAN MICHAEL CARDENAS CARDENAS  2022/04/27 19:00:34.560000000
14                                 NaN  2023/09/20 10:10:42.140000000
15                                 NaN  2024/02/20 11:06:20.240000000
16                                 NaN  2023/04/25 06:33:24.130000000
17       KLEBER RODOLFO SUAREZ ALCIVAR  2022/04/27 16:58:25.327000000
18                                 NaN  2022/04/27 05:40:38.417000000
19                                 NaN  2023/01/12 09:52:51.043000000

[20 rows x 36 columns]